### ISSUE TITLE
Prints lots of `unable to normalize group-resource le from label` errors

### ISSUE THREAD

**Issue by discordianfish** [DirectXMan12/k8s-prometheus-adapter#101]

**Comment by DirectXMan12** [comment]
This should really just be info-level I think.  It's because the default config is trying to consider all labels as group-resources during metrics-discovery.  In the mean time, you can either ignore them or change the default config.

Maybe weuld have a way to just explicitly ignore certain labels during discovery?

**Comment by discordianfish** [comment]
@DirectXMan12 Happening on `metric_namer.go:278`. This happens with the default config btw
