### ISSUE TITLE
Configure metric discovery to use same defaults that are in official kubernetes integration config

### ISSUE THREAD

**Issue by itskingori** [DirectXMan12/k8s-prometheus-adapter#40]
Conjecture here, but I'm guessing most people will set up Prometheus for Kubernetes using [the official out of the box integration config][1]. Which is pretty good IMHO. I'd like to suggest that you support that default (opinionated) config so that this tool works out of the box. That way you avoid having to do this:

```diff
diff --git a/common/resources/prometheus/server/02_config_maps.yml b/common/resources/prometheus/server/02_config_maps.yml
index 354afe625..cfb734c56 100644
--- a/common/resources/prometheus/server/02_config_maps.yml
+++ b/common/resources/prometheus/server/02_config_maps.yml
@@ -81,10 +81,10 @@ data:
             regex: __meta_kubernetes_service_label_(.+)
           - source_labels: [__meta_kubernetes_namespace]
             action: replace
-            target_label: kubernetes_namespace
+            target_label: namespace
           - source_labels: [__meta_kubernetes_service_name]
             action: replace
-            target_label: kubernetes_name
+            target_label: service
       - job_name: 'kubernetes-services'
         metrics_path: /probe
         params:
@@ -104,9 +104,9 @@ data:
           - action: labelmap
             regex: __meta_kubernetes_service_label_(.+)
           - source_labels: [__meta_kubernetes_namespace]
-            target_label: kubernetes_namespace
+            target_label: namespace
           - source_labels: [__meta_kubernetes_service_name]
-            target_label: kubernetes_name
+            target_label: service
       - job_name: 'kubernetes-ingresses'
         metrics_path: /probe
         params:
@@ -128,9 +128,9 @@ data:
             - action: labelmap
               regex: __meta_kubernetes_ingress_label_(.+)
             - source_labels: [__meta_kubernetes_namespace]
-              target_label: kubernetes_namespace
+              target_label: namespace
             - source_labels: [__meta_kubernetes_ingress_name]
-              target_label: kubernetes_name
+              target_label: ingress
       - job_name: 'kubernetes-pods'
         kubernetes_sd_configs:
           - role: pod
@@ -151,7 +151,7 @@ data:
             regex: __meta_kubernetes_pod_label_(.+)
           - source_labels: [__meta_kubernetes_namespace]
             action: replace
-            target_label: kubernetes_namespace
+            target_label: namespace
           - source_labels: [__meta_kubernetes_pod_name]
             action: replace
-            target_label: kubernetes_pod_name
+            target_label: pod
```

Thoughts?

[1]: https://github.com/prometheus/prometheus/blob/47538cf6cebbc143076043c5561d0f2a2c16ab6a/documentation/examples/prometheus-kubernetes.yml

**Comment by DirectXMan12** [comment]
We don't necessarily want to autoinject the pod name at that label, because you might have metrics coming from one pod which describe another (e.g. coming from an ingress controller, describing ingress objects), and you don't want those metrics being associated in the API with the original pod, or overwriting the listed pod with the pod the metrics came from.

**Comment by itskingori** [comment]
@DirectXMan12 Cool. I knew there was a reason, just wanted to understand what it was.

**Comment by huxiaoliang** [comment]
@DirectXMan12  @itskingori  I encountered same issue that message "metric xxx not registered" from function `QueryForMetric`, which caused metric discovery functionality doesn't work by using default [prometheus-kubernetes.yml](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml), then I try add `--label-prefix=kubernetes_`, it still did not work, only patch prometheus-kubernetes.yml diff provide by @itskingori can workaround.

I think the root cause is that you can't use --label-prefix=kubernetes_ to map `kubernetes_ namespaces` and kubernetes_pod_name` in the same time. (take job_name: 'kubernetes-pods' as an example)
